### ISSUE TITLE
Add code of conduct

### ISSUE THREAD

**Issue by UCGisWeek** [UCGisWeek/2020VirtualConference#13]

**Comment by UCGisWeek** [comment]
Also not as time-sensitive.  No text yet.  Thanks, Danielle

**Comment by amywork20** [comment]
UC GIS Week Code of Conduct

We expect participants to follow these rules at UC GIS Week virtual event, related social events, online forums, and on social media 

UC GIS Week is dedicated to providing a harassment-free experience for everyone whether in physical or virtual spaces. We do not tolerate harassment of community members or event participants in any form. Sexual language and imagery is not appropriate for any event venue, including talks, except as described below under specific circumstances. Participants violating these rules may be sanctioned or expelled from the event at the discretion of the event organizers.

Harassment includes offensive verbal comments related to gender, gender identity and expression, sexual orientation, disability, group status, physical appearance, body size, race, religion, sexual images in public spaces, deliberate intimidation, stalking, following, unwelcome photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention. Participants asked to stop any harassing behavior are expected to comply immediately.

Presenters at the virtual and exhibitors in the map gallery or similar activities are also subject to the anti-harassment policy. In particular, presenters and exhibitors should not use sexualized images, activities, or other material, or otherwise create a sexualized environment. However, within the context of academic, artistic, and professional practices of cartography, critical examination of beliefs and viewpoints does not, by itself, constitute hostile conduct or harassment. Similarly, use of sexual imagery or language in the context of a professional discussion or presentation might not constitute hostile conduct or harassment.

If a UC GIS Week participant engages in harassing behavior, the meeting organizers may take any action they deem appropriate, including warning the offender or expulsion from the event.

If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact the session moderator, email ucgisweek@gmail.com, or reach out to a member of the conference staff on UC GIS Slack immediately.  Committee members can be identified on Slack with a 📍 icon next to their names.

Committee members notified will communicate immediately with anyone who reports an issue and will work quickly to address the problem.

We value your attendance. UC GIS Week Committee organizers will be happy to assist anyone experiencing harassment to feel safe for the duration of the conference. If you would prefer to make a report electronically, please email ucgisweek@gmail.com, which we will monitor for alerts during the conference.

If you have any questions about this policy, please email ucgisweek@gmail.com or find a Committee Member on Slack.

This code of conduct policy is based in part on the example policy from the NACIS Code of Conduct, Geek Feminism wiki, created by the Ada Initiative and other volunteers.

**Comment by amywork20** [comment]
Here's the link to the Google Doc with example Code of Conducts:  https://docs.google.com/document/d/1l0J2lqICVlKv_rpdx_Pgv6ePHvf0b7mVzbogvcO2rgo/edit

**Comment by UCGisWeek** [comment]
Added a page and then linked to it from the schedule.
